# Generated by Django 3.1.1 on 2022-03-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title_image',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='article/images'),
        ),
    ]
