# Generated by Django 3.1.1 on 2022-04-17 14:22

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220323_0418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('verification_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='articlecomment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articlecomment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='articlecommentvote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='articlecommentvote',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='articlecommentvote',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='articlevote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='articlevote',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articlevote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='discussioninvitation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='discussioninvitation',
            name='discussion',
        ),
        migrations.RemoveField(
            model_name='discussioninvitation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='discussionmessage',
            name='discussion',
        ),
        migrations.RemoveField(
            model_name='discussionmessage',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ArticleComment',
        ),
        migrations.DeleteModel(
            name='ArticleCommentVote',
        ),
        migrations.DeleteModel(
            name='ArticleVote',
        ),
        migrations.DeleteModel(
            name='Discussion',
        ),
        migrations.DeleteModel(
            name='DiscussionInvitation',
        ),
        migrations.DeleteModel(
            name='DiscussionMessage',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
