# Generated by Django 3.1.1 on 2022-05-16 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220417_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.IntegerField(blank=True, null=True)),
                ('loan_term', models.IntegerField(blank=True, null=True)),
                ('loan_region', models.CharField(blank=True, max_length=140)),
                ('name', models.CharField(blank=True, max_length=140)),
                ('city', models.CharField(blank=True, max_length=140)),
                ('phone_number', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=140)),
                ('old_name', models.CharField(blank=True, max_length=140)),
                ('passport_photo_one', models.ImageField(blank=True, null=True, upload_to='passport')),
                ('passport_photo_two', models.ImageField(blank=True, null=True, upload_to='passport')),
                ('passport_photo_three', models.ImageField(blank=True, null=True, upload_to='passport')),
                ('passport_photo_four', models.ImageField(blank=True, null=True, upload_to='passport')),
                ('passport_photo_five', models.ImageField(blank=True, null=True, upload_to='passport')),
                ('passport_series', models.CharField(blank=True, max_length=140)),
                ('passport_number', models.CharField(blank=True, max_length=140)),
                ('passport_issue_date', models.DateField(blank=True, null=True)),
                ('passport_code', models.CharField(blank=True, max_length=140)),
                ('passport_issued_by', models.CharField(blank=True, max_length=140)),
                ('passport_place_of_birth', models.CharField(blank=True, max_length=140)),
                ('passport_date_of_birth', models.DateField(blank=True, null=True)),
                ('old_passport_series', models.CharField(blank=True, max_length=140)),
                ('old_passport_number', models.CharField(blank=True, max_length=140)),
                ('old_passport_issue_date', models.DateField(blank=True, null=True)),
                ('old_passport_code', models.CharField(blank=True, max_length=140)),
                ('old_passport_issued_by', models.CharField(blank=True, max_length=140)),
                ('old_passport_place_of_birth', models.CharField(blank=True, max_length=140)),
                ('old_passport_date_of_birth', models.DateField(blank=True, null=True)),
                ('current_address', models.CharField(blank=True, max_length=280)),
                ('current_apartments_number', models.CharField(blank=True, max_length=140)),
                ('has_no_current_address', models.BooleanField(default=False)),
                ('registration_address', models.CharField(blank=True, max_length=280)),
                ('registration_apartments_number', models.CharField(blank=True, max_length=140)),
                ('monthly_income', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
