# Generated by Django 3.1.1 on 2022-05-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220516_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
