# Generated by Django 3.1.1 on 2022-05-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_loanapplication_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('under_review', 'На рассмотрении'), ('declined', 'Отклонена'), ('approved', 'Одобрена')], default='under_review', max_length=140),
        ),
    ]
