# Generated by Django 3.1.1 on 2022-05-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_loanapplication_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanapplication',
            options={'verbose_name': 'заявление', 'verbose_name_plural': 'заявления'},
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(blank=True, choices=[('under_review', 'На рассмотрении'), ('declined', 'Отклонена'), ('approved', 'Одобрена')], default='under_review', max_length=140),
        ),
    ]
