# Generated by Django 3.1.1 on 2022-10-13 08:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20221010_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('limit_descr', models.CharField(max_length=100)),
                ('transaction_policy', models.CharField(max_length=100)),
                ('payment_policy', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeToChoose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('under_review', 'На рассмотрении'), ('declined', 'Отклонена'), ('approved', 'Одобрена')], default='under_review', max_length=140)),
                ('inn', models.CharField(max_length=12)),
                ('company_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=120)),
                ('basis', models.CharField(max_length=100)),
                ('mail_address', models.CharField(max_length=120)),
                ('supreme_management_body', models.CharField(max_length=100)),
                ('supervisor', models.CharField(max_length=100)),
                ('supervisor_inn', models.CharField(max_length=12)),
                ('supervisory', models.CharField(max_length=100)),
                ('collegiate_body', models.CharField(max_length=100)),
                ('collegiate_person', models.CharField(max_length=100)),
                ('employers_volume', models.IntegerField()),
                ('salary_debt', models.IntegerField()),
                ('company_group_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('group_members', models.JSONField(max_length=300)),
                ('loan_amount', models.IntegerField()),
                ('loan_time', models.IntegerField()),
                ('loan_rate', models.FloatField()),
                ('documents', models.ImageField(blank=True, null=True, upload_to='documents')),
                ('rate', models.CharField(max_length=100)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=140)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.tariffplan')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.typetochoose')),
            ],
            options={
                'verbose_name': 'заявление',
                'verbose_name_plural': 'заявления',
            },
        ),
    ]
