# Generated by Django 3.1.1 on 2022-10-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_loanrequest_tariffplan_typetochoose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='start_date',
            field=models.DateField(),
        ),
    ]
