# Generated by Django 3.1.1 on 2022-10-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20221013_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrequest',
            old_name='address',
            new_name='legal_address',
        ),
        migrations.RenameField(
            model_name='loanrequest',
            old_name='mail_address',
            new_name='legal_mail_address',
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='physic_address',
            field=models.CharField(default=str, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='real_mail_address',
            field=models.CharField(default=str, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
