# Generated by Django 3.1.1 on 2022-10-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20221014_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='first_passport_page',
            field=models.ImageField(blank=True, null=True, upload_to='documents'),
        ),
    ]
