# Generated by Django 3.1.1 on 2022-10-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20221015_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequest',
            name='account_own_living',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='account_own_role',
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='account_onw_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='accownt_own_living',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='account_own_gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='account_own_registration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='assigned_publ_pers_relation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='basis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='contact_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='foreign_doc_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='foreign_doc_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='foreign_doc_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='foreign_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='foreign_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='licence_date_issue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='licence_issued_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='licence_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='licence_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='licence_validity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='licenced_activity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='loan_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='loan_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='loan_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='rate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='supervisory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
