# Generated by Django 3.1.1 on 2022-10-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20221016_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='account_onw_inn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='account_own_citizenship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='account_own_lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='account_own_mail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='account_own_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='account_own_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='account_own_piece',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='account_own_surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='accownt_own_living',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='collegiate_body',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='collegiate_person_fio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='legal_address',
            field=models.JSONField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='mail_address',
            field=models.JSONField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='physic_address',
            field=models.JSONField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='supreme_management_body',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='supreme_management_inn',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='supreme_management_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
