# Generated by Django 3.1.1 on 2022-10-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20221016_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequest',
            name='legal_address',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='mail_address',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='physic_address',
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='addresses',
            field=models.JSONField(default='{}', max_length=300),
            preserve_default=False,
        ),
    ]
