# Generated by Django 3.1.1 on 2022-10-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20221016_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='salary_debt',
            field=models.BigIntegerField(),
        ),
    ]
