# Generated by Django 3.1.1 on 2022-10-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20221017_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrequest',
            old_name='collegiate_person_fio',
            new_name='foreigner_doc_number',
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='foreigner_doc_issued',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='foreigner_doc_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='foreigner_doc_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='foreigner_doc_validity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='collegiate_body',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='supervisory',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
    ]
