# Generated by Django 3.1.1 on 2022-10-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20221019_0627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrequest',
            old_name='supervisory',
            new_name='supervisory_body',
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='collegiate_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='supervisory_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
