# Generated by Django 3.1.1 on 2022-10-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20221025_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='account_birth_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='account_datebirth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='division_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='doc_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='doc_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='doc_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='issued_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
