# Generated by Django 3.1.1 on 2022-10-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20221025_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
