# Generated by Django 3.1.1 on 2022-10-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20221025_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='inn',
            field=models.CharField(max_length=20),
        ),
    ]
