# Generated by Django 3.1.1 on 2022-10-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20221025_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='company_group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='group_members',
            field=models.JSONField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
