# Generated by Django 3.1.1 on 2022-10-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20221027_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='last_status',
            field=models.CharField(blank=True, choices=[('На рассмотрении', 'На рассмотрении'), ('Отклонена', 'Отклонена'), ('Одобрена', 'Одобрена'), ('Доработка заявки', 'Доработка заявки')], default='На рассмотрении', max_length=140),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('На рассмотрении', 'На рассмотрении'), ('Отклонена', 'Отклонена'), ('Одобрена', 'Одобрена'), ('Доработка заявки', 'Доработка заявки')], default='На рассмотрении', max_length=140),
        ),
    ]
