# Generated by Django 3.1.1 on 2022-10-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20221028_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='last_status',
            field=models.CharField(blank=True, choices=[('under_review', 'На рассмотрении'), ('declined', 'Отклонена'), ('approved', 'Одобрена'), ('update', 'Доработка заявки')], default='under_review', max_length=140),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('under_review', 'На рассмотрении'), ('declined', 'Отклонена'), ('approved', 'Одобрена'), ('update', 'Доработка заявки')], default='under_review', max_length=140),
        ),
    ]
