# Generated by Django 3.1.1 on 2022-11-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20221102_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='addresses',
            field=models.JSONField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='contact_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
