# Generated by Django 3.1.1 on 2022-11-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20221102_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrequest',
            old_name='is_finish',
            new_name='is_finished',
        ),
    ]
