# Generated by Django 3.1.1 on 2022-11-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_loanrequest_last_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.FileField(upload_to='documents')),
            ],
        ),
    ]
