# Generated by Django 3.1.1 on 2022-11-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_passportfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='account_operations',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='addresses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='beneficiaries',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='cash_source',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='collegiate_body',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='collegiate_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='company_group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='employers_volume',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='licence_issued_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='licence_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='licence_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='licenced_activity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='operation_volume',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='outside_contracts_volume',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='planned_operations',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='state_employers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='sum_per_month',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='supervisory_body',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='supervisory_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='supreme_management_body',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='supreme_management_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='tariff',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='limit_descr',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='payment_policy',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='transaction_policy',
            field=models.CharField(max_length=255),
        ),
    ]
