# Generated by Django 3.1.1 on 2022-11-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20221103_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrequest',
            old_name='collegiate_name',
            new_name='collegiate_person',
        ),
        migrations.RenameField(
            model_name='loanrequest',
            old_name='collegiate_body',
            new_name='listCollegialExecutiveBody',
        ),
        migrations.RenameField(
            model_name='loanrequest',
            old_name='supervisory_body',
            new_name='listSupervisotyBoardPersone',
        ),
        migrations.RenameField(
            model_name='loanrequest',
            old_name='supervisory_name',
            new_name='supervisotyBoardPersone_name',
        ),
    ]
