# Generated by Django 3.1.1 on 2022-11-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20221107_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='is_collegiate_body',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='is_supervisoty',
            field=models.BooleanField(default=False),
        ),
    ]
