# Generated by Django 3.1.1 on 2022-12-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20221108_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
