# Generated by Django 3.1.1 on 2022-12-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_loanrequest_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='status_description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
