# Generated by Django 3.1.1 on 2022-12-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_loanrequest_ogrn'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='information_goals',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
