# Generated by Django 3.1.1 on 2022-12-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20221222_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrequest',
            old_name='planning',
            new_name='additional_products',
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='codeword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
