# Generated by Django 3.1.1 on 2022-12-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_auto_20221222_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='contact_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
