# Generated by Django 3.1.1 on 2022-12-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20221223_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='document_certifying_identity_executive',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='document_confirming_real_activity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='document_licenses',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
