# Generated by Django 3.1.1 on 2022-12-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_auto_20221223_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='is_conditions',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='opf',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
