# Generated by Django 3.1.1 on 2022-12-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_auto_20221226_0617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrequest',
            old_name='information_counterparties2',
            new_name='information_counterparties_two',
        ),
        migrations.RenameField(
            model_name='loanrequest',
            old_name='name_organization2',
            new_name='name_organization_two',
        ),
    ]
