# Generated by Django 3.1.1 on 2022-12-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_auto_20221226_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequest',
            name='informationGoals',
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='planned_operations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='planned_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
