# Generated by Django 3.1.1 on 2023-01-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_auto_20221228_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_sms_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
