# Generated by Django 3.1.1 on 2023-02-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_user_last_sms_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrequest',
            old_name='short_name',
            new_name='short',
        ),
    ]
