# Generated by Django 3.1.1 on 2023-02-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_auto_20230208_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='hasConstantPayers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='hasConstantPayersDetails',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='hasConstantRecipient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='hasConstantRecipientDetails',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
