# Generated by Django 3.1.1 on 2023-02-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_auto_20230213_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='last_status',
            field=models.CharField(blank=True, default='under_review', max_length=140),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(blank=True, default='under_review', max_length=140),
        ),
    ]
