# Generated by Django 3.1.1 on 2023-03-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_auto_20230217_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='additional_inforamtion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
