version: "3.4"

services:
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  rabbitmq:
    image: rabbitmq:3.8.3
    ports:
      - 5672:5672
    env_file:
      - .env
      - .env.secret
  django:
    build:
      context: ../../
      dockerfile: ./Docker/dev/python/Dockerfile
      target: django
    command: >
      python /usr/src/app/manage.py runserver 0.0.0.0:8000
      --settings=project.settings.dev
    volumes:
      - ../../django/:/usr/src/app/
      - vscode-loan-application-bot-volume:/usr/src/app/.vscode-server/extensions
    ports:
      - 8000:8000
    env_file:
      - .env
      - .env.secret
    stdin_open: true
    tty: true
    depends_on:
      - db
  celery:
    build:
      context: ../../
      dockerfile: ./Docker/dev/python/Dockerfile
      target: celery
    command: celery -A project worker -l info --concurrency=1
    volumes:
      - ../../django:/usr/src/app/
    env_file:
      - .env
      - .env.secret
    stdin_open: true
    tty: true
    depends_on:
      - db
      - rabbitmq
  telegram:
    build:
      context: ../../
      dockerfile: ./Docker/dev/python/Dockerfile
      target: telegram
    command: python telegram-bot/bot.py
    volumes:
      - ../../django:/usr/src/app/
    env_file:
      - .env
      - .env.secret
    stdin_open: true
    tty: true
    depends_on:
      - django
      - celery
  vuejs:
    build:
      context: ../../
      dockerfile: ./Docker/dev/vuejs/Dockerfile
    command: yarn serve
    volumes:
      - ../../vuejs/:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    env_file:
      - .env
      - .env.secret
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  vscode-loan-application-bot-volume:
